name: PR Tag Release
on:
  pull_request:
    types:
      - closed
    branches:
      - "main"

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'release:major') || contains(github.event.pull_request.labels.*.name, 'release:minor') || contains(github.event.pull_request.labels.*.name, 'release:patch')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        label: ${{github.event.pull_request.labels.*.name}}
        
    steps:
      - name: Check Tags
        run: |
          if [[ !startsWith(matrix.label, 'release:') ]]; then exit 0

      - name: Testing Labels
        run: |
          echo "-------> ${{github.event.pull_request.labels}}"
          release_type=`echo ${{matrix.label}} | awk -F':' '{print $NF}'`
          echo "RELEASE_TYPE=${release_type}" >> $GITHUB_ENV
          echo "Releasing: ${release_type}"
          
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ env.RELEASE_TYPE }}
