name: PR Tag Release
on:
  pull_request:
    types:
      - "merged"
    branches:
      - "main"

jobs:
  tag-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        label: ${{github.event.pull_request.labels.*.name}}
        
    steps:
      - if: startsWith(matrix.label, 'release:')
        name: Testing Labels
        run: |
          echo "-------> ${{github.event.pull_request.labels}}"
          release_type=`echo ${{matrix.label}} | awk -F':' '{print $NF}'`
          echo "RELEASE_TYPE=${release_type}" >> $GITHUB_ENV
          echo "Releasing: ${release_type}"
          
      - if: startsWith(matrix.label, 'release:')
        name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ env.RELEASE_TYPE }}
