name: PR Tag Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        label: ${{ github.event.pull_request.labels.*.name }}
        
    steps:
      - if: startsWith(matrix.label, 'release:')
        name: Testing Labels
        run: |
          release_type=`echo ${{matrix.label}} | awk -F':' '{print $NF}'`
          echo "RELEASE_TYPE=${release_type}" >> $GITHUB_ENV
          echo "Releasing: ${release_type}"
          
#       - if: startsWith(matrix.label, 'release:')
#         name: Bump version and push tag
#         id: tag_version
#         uses: mathieudutour/github-tag-action@v6.0
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           default_bump: ${{ env.RELEASE_TYPE }}

      - if: startsWith(matrix.label, 'release:')
        name: Version Info
        run: |
          echo "${{ steps.tag_version.outputs.new_tag }}"

      - if: startsWith(matrix.label, 'release:')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          generateReleaseNotes: true
          prerelease: false
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
